### ISSUE TITLE
This example lacks usage examples or test code samples

### ISSUE THREAD

**Issue by ghost** [vsouza/go-graphql-subscription#1]
It would be cool if you provide usage examples or automated tests. It is not clear how to actually use the example.

**Comment by vsouza** [comment]
@Xeizzen thanks for reporting. I'll archive this project because the support of subscriptions by the `go-graphql` isn't good, so, I'm concerned about people using this project and losing their time or receiving different results.

I recommend this project: [https://github.com/functionalfoundry/graphqlws](https://github.com/functionalfoundry/graphqlws) seems to be a good implementation of Subscriptions with Go.
